CREATE TABLE GENERATOR (
	GEN_NAME VARCHAR(20) NOT NULL,
	GEN_VALUE BIGINT NOT NULL DEFAULT 1000,
	PRIMARY KEY (GEN_NAME)
) ENGINE=INNODB;

CREATE TABLE USER (
	USER_KEY BIGINT NOT NULL,
	EMAIL VARCHAR(255) NOT NULL,
	UNIQUE INDEX (EMAIL), 
	PRIMARY KEY (USER_KEY)
) ENGINE=INNODB;

CREATE TABLE LEVEL (
	LEVEL_ID VARCHAR(20) NOT NULL,
	PRIMARY KEY (LEVEL_ID)
) ENGINE=INNODB;

CREATE TABLE AUDIT_LOG (
	AUDIT_LOG_KEY BIGINT NOT NULL,
	USER_KEY BIGINT NOT NULL,
	ACTION CHAR(3) NOT NULL,
	DATE DATE NOT NULL,
	PRIMARY KEY (AUDIT_LOG_KEY),
	CONSTRAINT FK_AUDIT_LOG_USER FOREIGN KEY (USER_KEY) REFERENCES USER (USER_KEY)
) ENGINE=INNODB;

CREATE TABLE LEVEL_ATTEMPT (
	LEVEL_ATTEMPT_KEY BIGINT NOT NULL,
	LEVEL_ID VARCHAR(20) NOT NULL,
	AUDIT_LOG_KEY BIGINT NOT NULL,
	STATUS CHAR(1),
	TIME DOUBLE,
	STEPS INT,
	LOST_UNITS INT,
	PRIMARY KEY (LEVEL_ATTEMPT_KEY),
	CONSTRAINT FK_LEVEL_ATTEMPT_AUDIT_LOG FOREIGN KEY (AUDIT_LOG_KEY) REFERENCES AUDIT_LOG (AUDIT_LOG_KEY)
) ENGINE=INNODB;

CREATE TABLE LEVEL_RESULT_TIME (
	LEVEL_RESULT_KEY BIGINT NOT NULL,
	LEVEL_ID VARCHAR(20) NOT NULL,
	USER_KEY BIGINT NOT NULL,
	VALUE DOUBLE NOT NULL,
	DATE TIMESTAMP NOT NULL,
	PRIMARY KEY (LEVEL_RESULT_KEY),
	CONSTRAINT FK_LR_TIME_USER FOREIGN KEY (USER_KEY) REFERENCES USER (USER_KEY),
	CONSTRAINT FK_LR_TIME_LEVEL FOREIGN KEY (LEVEL_ID) REFERENCES LEVEL (LEVEL_ID)
) ENGINE=INNODB;
ALTER TABLE LEVEL_RESULT_TIME ADD UNIQUE U_LRT_USER (LEVEL_ID, USER_KEY);

CREATE TABLE LEVEL_RESULT_LOST_UNITS (
	LEVEL_RESULT_KEY BIGINT NOT NULL,
	LEVEL_ID VARCHAR(20) NOT NULL,
	USER_KEY BIGINT NOT NULL,
	VALUE INT NOT NULL,
	DATE TIMESTAMP NOT NULL,
	PRIMARY KEY (LEVEL_RESULT_KEY),
	CONSTRAINT FK_LR_LOST_UNITS_USER FOREIGN KEY (USER_KEY) REFERENCES USER (USER_KEY),
	CONSTRAINT FK_LR_LOST_UNITS_LEVEL FOREIGN KEY (LEVEL_ID) REFERENCES LEVEL (LEVEL_ID)
) ENGINE=INNODB;
ALTER TABLE LEVEL_RESULT_LOST_UNITS ADD UNIQUE U_LRLU_USER (LEVEL_ID, USER_KEY);

CREATE TABLE LEVEL_RESULT_STEPS (
	LEVEL_RESULT_KEY BIGINT NOT NULL,
	LEVEL_ID VARCHAR(20) NOT NULL,
	USER_KEY BIGINT NOT NULL,
	VALUE INT NOT NULL,
	DATE TIMESTAMP NOT NULL,
	PRIMARY KEY (LEVEL_RESULT_KEY),
	CONSTRAINT FK_LR_STEPS_USER FOREIGN KEY (USER_KEY) REFERENCES USER (USER_KEY),
	CONSTRAINT FK_LR_STEPS_LEVEL FOREIGN KEY (LEVEL_ID) REFERENCES LEVEL (LEVEL_ID)
) ENGINE=INNODB;
ALTER TABLE LEVEL_RESULT_STEPS ADD UNIQUE U_LRS_USER (LEVEL_ID, USER_KEY);