INSERT INTO GENERATOR (GEN_NAME) VALUES ('USER_GEN');
INSERT INTO GENERATOR (GEN_NAME) VALUES ('LEVEL_RESULT_GEN');
INSERT INTO GENERATOR (GEN_NAME) VALUES ('AUDIT_LOG_GEN');

INSERT INTO USER (USER_KEY, EMAIL)
	VALUES((SELECT MAX(GEN_VALUE) FROM GENERATOR WHERE GEN_NAME = 'USER_GEN'), 'makseemkadragun@gmail.com');
UPDATE GENERATOR SET GEN_VALUE = GEN_VALUE + 1 WHERE GEN_NAME = 'USER_GEN';
INSERT INTO USER (USER_KEY, EMAIL)
	VALUES((SELECT MAX(GEN_VALUE) FROM GENERATOR WHERE GEN_NAME = 'USER_GEN'), 'test1@gmail.com');
UPDATE GENERATOR SET GEN_VALUE = GEN_VALUE + 1 WHERE GEN_NAME = 'USER_GEN';
INSERT INTO USER (USER_KEY, EMAIL)
	VALUES((SELECT MAX(GEN_VALUE) FROM GENERATOR WHERE GEN_NAME = 'USER_GEN'), 'test2@gmail.com');
UPDATE GENERATOR SET GEN_VALUE = GEN_VALUE + 1 WHERE GEN_NAME = 'USER_GEN';
INSERT INTO USER (USER_KEY, EMAIL)
	VALUES((SELECT MAX(GEN_VALUE) FROM GENERATOR WHERE GEN_NAME = 'USER_GEN'), 'test3@gmail.com');
UPDATE GENERATOR SET GEN_VALUE = GEN_VALUE + 1 WHERE GEN_NAME = 'USER_GEN';

INSERT INTO LEVEL (LEVEL_ID) VALUE ("ozo.level.0");
INSERT INTO LEVEL (LEVEL_ID) VALUE ("ozo.level.1");
INSERT INTO LEVEL (LEVEL_ID) VALUE ("ozo.level.2");
INSERT INTO LEVEL (LEVEL_ID) VALUE ("ozo.level.3");