INSERT INTO GENERATOR (GEN_NAME) VALUES ('USER_GEN');
INSERT INTO GENERATOR (GEN_NAME) VALUES ('LEVEL_RESULT_GEN');
INSERT INTO GENERATOR (GEN_NAME) VALUES ('AUDIT_LOG_GEN');

INSERT INTO USER (USER_KEY, USER_ID, USER_NAME, EMAIL)
	VALUES((SELECT MAX(GEN_VALUE) FROM GENERATOR WHERE GEN_NAME = 'USER_GEN'), 'id0', 'makseemka', 'makseemkadragun@gmail.com');
UPDATE GENERATOR SET GEN_VALUE = GEN_VALUE + 1 WHERE GEN_NAME = 'USER_GEN';
INSERT INTO USER (USER_KEY, USER_ID, USER_NAME, EMAIL)
	VALUES((SELECT MAX(GEN_VALUE) FROM GENERATOR WHERE GEN_NAME = 'USER_GEN'), 'id1', 'test1', 'test1@gmail.com');
UPDATE GENERATOR SET GEN_VALUE = GEN_VALUE + 1 WHERE GEN_NAME = 'USER_GEN';
INSERT INTO USER (USER_KEY, USER_ID, USER_NAME, EMAIL)
	VALUES((SELECT MAX(GEN_VALUE) FROM GENERATOR WHERE GEN_NAME = 'USER_GEN'), 'id2', 'test2', 'test2@gmail.com');
UPDATE GENERATOR SET GEN_VALUE = GEN_VALUE + 1 WHERE GEN_NAME = 'USER_GEN';
INSERT INTO USER (USER_KEY, USER_ID, USER_NAME, EMAIL)
	VALUES((SELECT MAX(GEN_VALUE) FROM GENERATOR WHERE GEN_NAME = 'USER_GEN'), 'id3', 'test3', 'test3@gmail.com');
UPDATE GENERATOR SET GEN_VALUE = GEN_VALUE + 1 WHERE GEN_NAME = 'USER_GEN';

INSERT INTO LEVEL (LEVEL_ID) VALUES ('ozo.level.0');
INSERT INTO LEVEL (LEVEL_ID) VALUES ('ozo.level.1');
INSERT INTO LEVEL (LEVEL_ID) VALUES ('ozo.level.2');
INSERT INTO LEVEL (LEVEL_ID) VALUES ('ozo.level.3');
