CREATE TABLE GENERATOR (
	GEN_NAME VARCHAR(20) NOT NULL,
	GEN_VALUE BIGINT NOT NULL DEFAULT 1000,
	PRIMARY KEY (GEN_NAME)
) ENGINE=INNODB;

CREATE TABLE USER (
	USER_KEY BIGINT NOT NULL,
	USER_ID VARCHAR(36) NOT NULL,
	USER_NAME VARCHAR(32) NOT NULL,
	EMAIL VARCHAR(255) NOT NULL,
	UNIQUE INDEX (USER_ID), 
	PRIMARY KEY (USER_KEY)
) ENGINE=INNODB;
ALTER TABLE USER ADD UNIQUE U_USER_ID (USER_ID);
ALTER TABLE USER ADD UNIQUE U_USER_NAME (USER_NAME);

CREATE TABLE LEVEL (
	LEVEL_ID VARCHAR(36) NOT NULL,
	PRIMARY KEY (LEVEL_ID)
) ENGINE=INNODB;

CREATE TABLE AUDIT_EVENT (
	AUDIT_EVENT_KEY BIGINT NOT NULL,
	USER_KEY BIGINT NOT NULL,
	ACTION CHAR(3) NOT NULL,
	DATE DATETIME(3) NOT NULL,
	PRIMARY KEY (AUDIT_EVENT_KEY),
	CONSTRAINT FK_AUDIT_LOG_USER FOREIGN KEY (USER_KEY) REFERENCES USER (USER_KEY)
) ENGINE=INNODB;

CREATE TABLE LEVEL_ATTEMPT (
	LEVEL_ATTEMPT_KEY BIGINT NOT NULL,
	LEVEL_ID VARCHAR(36) NOT NULL,
	AUDIT_EVENT_KEY BIGINT NOT NULL,
	STATUS CHAR(1),
	TIME INT,
	STEPS INT,
	LOST_UNITS INT,
	PRIMARY KEY (LEVEL_ATTEMPT_KEY),
	CONSTRAINT FK_LEVEL_ATTEMPT_AUDIT_LOG FOREIGN KEY (AUDIT_EVENT_KEY) REFERENCES AUDIT_EVENT (AUDIT_EVENT_KEY)
) ENGINE=INNODB;

CREATE TABLE LEVEL_RESULT (
	LEVEL_RESULT_KEY BIGINT NOT NULL,
	LEVEL_ID VARCHAR(36) NOT NULL,
	USER_KEY BIGINT NOT NULL,
	NAME VARCHAR(12) NOT NULL,
	VALUE DOUBLE NOT NULL,
	DATE DATETIME(3) NOT NULL,
	PRIMARY KEY (LEVEL_RESULT_KEY),
	CONSTRAINT FK_LR_TIME_USER FOREIGN KEY (USER_KEY) REFERENCES USER (USER_KEY),
	CONSTRAINT FK_LR_TIME_LEVEL FOREIGN KEY (LEVEL_ID) REFERENCES LEVEL (LEVEL_ID)
) ENGINE=INNODB;
ALTER TABLE LEVEL_RESULT ADD UNIQUE U_LRT_USER (LEVEL_ID, NAME, USER_KEY);
